USE spotify;

# List the number of films per category.
SELECT name, count(film_id)
FROM category
INNER JOIN film_category
USING(category_id)
INNER JOIN film
USING(film_id)
GROUP BY category.name;

# Retrieve the store ID, city, and country for each store.
SELECT store.store_id, city.city, country.country
FROM store
INNER JOIN address
USING(address_id)
INNER JOIN city
USING(city_id)
INNER JOIN country
USING(country_id);


# Calculate the total revenue generated by each store in dollars.
SELECT store.store_id, SUM(payment.amount)
FROM store
INNER JOIN staff
USING(store_id)
INNER JOIN payment
USING (staff_id)
GROUP BY store_id;


# Determine the average running time of films for each category.

SELECT name, AVG(film.length)
FROM category
INNER JOIN film_category
USING (category_id)
INNER JOIN film
USING (film_id)
GROUP BY category.name;
